stages: 
  - deploy

deploy_346:
  stage: deploy
  only: 
    - DC1
  script:
    - cp sh/setup.sls /srv/salt/setup.sls
    - cp sh/upgrade.sls /srv/salt/upgrade.sls
    - tar -zcf /srv/salt/files/build.tar.gz . -X exclude.txt
    - salt -C 'G@roles:DC1' state.sls upgrade pillar='{"branch":"DC!"}'

deploy_all:
  stage: deploy
  only: 
    - master
  script:
    - cp sh/setup.sls /srv/salt/setup.sls
    - cp sh/upgrade.sls /srv/salt/upgrade.sls
    - tar -zcf /srv/salt/files/build.tar.gz . -X exclude.txt
    - salt \* state.sls upgrade pillar='{"branch":"master"}'

